### ISSUE TITLE
[Spell] Blessing of Sacrifice causes pushback

### ISSUE THREAD

**Issue by Rettiy** [SunstriderEmu/BugTracker#1737]
**Describe the bug**
Blessing of Sacrifice http://tbc.cavernoftime.com/spell=6940 http://tbc.cavernoftime.com/spell=20729 http://tbc.cavernoftime.com/spell=27147 http://tbc.cavernoftime.com/spell=27148 (I suppose all ranks, experienced on rank 1) gives Pushback to the caster while casting a spell, making it impossible to cast anything efficiently if the sacrificed target is being damaged.

Pushback is afaik currently caused only by redirected hits that would otherwise also cause pushback to the sacrificed target. That means dots do not cause pushback, while melee hits, moonfire, mind blast etc. (u get the point) do cause pushback.

**To Reproduce**
1. Cast Sacrifice on target
2. Hit target with melee/spells that cause pushback to the target
3. Cast spells as paladin
4. Notice pushback caused by Sacrifice

**Expected behavior**
Blessing of Sacrifice should never give any kind of pushback to the casting paladin, whatever the redirected damage is.

**Screenshots/videos**
Clips from Endless, watch the cast bar on the left.
https://clips.twitch.tv/GoldenDeadDonkeyPhilosoraptor
_pushback from Moonfire_
https://clips.twitch.tv/IncredulousFlirtyPeachAMPTropPunch
_pushback from melee and other things_

I don't think proof is neccessary since the current state is nonsense.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by kelno** [comment]
Thjanks for providing ids as well

**Comment by kelno** [comment]
Should be working with next restart

**Comment by Rettiy** [comment]
@kelno What I meant originally is that dots never caused pushback, that was always correctly working. So I'm kinda puzzled by _"Fixed DoT causing casting time pushback through Blessing of Sacrifice."_ in Changelog on the page.
The biggest problem still lies in any ordinary attack that would cause pushback that also causes pushback through sacrifice. So there probably was probably no change/improvement since dots never caused pushback on PTR anyway.

**Comment by Jerrythemagicdog** [comment]
Still causes pushback (rev. 13318)

**Comment by kylerogers334** [comment]
This problem still exists

**Comment by sadlogic** [comment]
dots on priest reflective shield also cause pushback, is that supposed to happen?

**Comment by kelno** [comment]
Fixed!
About reflective shield I don't know, if this is an issue please create a new issue for it
