### ISSUE TITLE
Summoning bug / target changing bug

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2250]
Summoning people as a warlock or with summoning stone.

There is some sort of bug/weird interaction with addons that is causing target to swap without user input.  If I target player 1 and start summoning.  Other members of my group can see that I either am not targetting the person my UI says I am targetting or that it will periodically change without me clicking on a new target (or my ui updating showing me a new target).  

Effectively what you must do to summon is 1 person clicks summon (either stone or warlock) and the final assisting person targets the person doing the summoning... and when it shows the correct target he clicks.  If the target changes he unclicks waits for the summoner to retarget the person and then he reclicks until you get lucky enough to channel the full summon on the correct target.

alternatively,, it seems like the first few seconds after choosing someone it is fine. so what you can watch others click your summon, wait till its about 1s from completing then click someone else in your party then reclick your intended target.  I have pretty high success with this method > 85%.

I also find that i have more success if i dont move my mouse at all after i click my target, but not 100% (but then again with an 4000 dpi mouse it may technically be moving even if i can't perceive it).  I have a decent success rate with this method probably around 65-75%.  

I have heard other people say that some people have "no problems".  I am using the exact client i use on warmane and i have never had any kind of issue with summoning or targetting there or on netherwing.  its something specific to endless or an interaction between endless and addons.

this bug is absolute cancer.  we rely so much on summoning and having to make extra shards plus the focus of 2-3 players to successfully summon someone is ... not a good experience.

**Comment by Godmatik** [comment]
In their most recent changelog it said this was fixed, but it might not be active yet.

**Comment by Jerrythemagicdog** [comment]
This is an issue for unit frames addons ElvUI and Xperl users (those are 100% confirmed). The addon pokes around for additional information about your party/raid members and switches your target without you intending to do so. The change we've implemented recently is that the target at the start of the cast gets stored and that person is summoned as a workaround for the issues these addons have. That still requires you to target the correct person at the start of the cast which apparently is displayed incorrectly and players de-target their current target and target their intended target before starting the cast.

**Comment by Denagul** [comment]
I hope there are plans to implement fixes to summoning regarding other cases besides elvui and xperl. I run Diamond threat meter/grid etc. so it sounds like those are intrusive for the time being. I suggest looking at those as well.

**Comment by tpageforfunzies** [comment]
Still getting the bug described above and not using any unit frame addons

**Comment by Ironjudgment** [comment]
Can confirm, bug is still active

**Comment by lukas155** [comment]
Bug is still active, I am not using any unit frame addon and have the same issue. HOWEVER it does have something to do with addons in general, as disabling ALL addons will stop this from happening.

**Comment by Jalapan** [comment]
@Jerrythemagicdog still bugged with standard unitframes and no addons

**Comment by Trolltilla** [comment]
Still bugged

**Comment by Denagul** [comment]
I did some testing on what addons cause summoning issues and have found 5 Troublesome addons: Gearscorelite, Procodile, NarkarDrums, Omen2 and Diamond Threat Meter...there may be more, however these 5 are the ones in my library that personally caused me issues

If my warlock with no troublesome addons enabled targets my warrior who has troublesome addons enabled then my warrior is now targetting my warlock as if my warrior "pulled aggro" on my warlock since i turned and targeted him much like how creatures and bosses often turn and target spells at random players such as Dalliah the Doomsayer's Shadow Wave.

Much like how in PVP if an alliance player is not targetting anything and you start casting into them, they will target you just because you started a cast toward them before it even lands. This PVP scenario should be the ONLY exception to someone targetting someone randomly without the player manually targetting something from their client.

Again...these addons did not prevent me from summoning properly on previous private servers so I'm confused why Endless is having such a problem with summons.

**Comment by Fittycal** [comment]
Can confirm this is still bugged

**Comment by Sheikthecatman** [comment]
Most likely fixed in [3f53477c8e68954fcddd14f64eb5908ecdc60855](https://github.com/kelno/sunstrider/commit/3f53477c8e68954fcddd14f64eb5908ecdc60855) which should be live.
